site: wgtwo

collections:
  pages:
    output: true
    permalink: /:name
  blogs:
    output: true
    permalink: /blog/:slug
  blog_eng:
    output: true
    permalink: /blog/:slug
  blog_updates:
    output: true
    permalink: /blog/:slug
  customer_stories:
    output: true
    permalink: /stories/:slug

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "blog_eng"
    values:
      layout: "blog"
  -
    scope:
      path: ""
      type: "blog_updates"
    values:
      layout: "blog"
  -
    scope:
      path: ""
      type: "customer_stories"
    values:
      layout: "page"

markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  
sass:
  style: compressed

plugins:
  - jekyll-paginate
  - jekyll-sitemap

paginate: 6
paginate_path: "/blog/page:num/"

gallery_types:
  carousel: Carousel
  grid: Grid
grid_columns:
  two: Two
  three: Three
  four: Four
  