basic_settings:
  site_title: WGTWO
  favicon_image: /images/favicon.png

header_settings:
  logo_image: /images/wgtwo-landscape-hvit-logo.png
  logo_image_orange: /images/wgtwo-landscape-orange-logo.png
  logo_image_blue: /images/wgtwo-landscape-blue-logo.png
  logo_width: 200

menu_settings:
  menu_items:
    - title: 'Customer Stories'
      url: '/customer-stories'
    - title: 'Why WGTWO'
      url: '/telco-core-network'
    - title: 'Blog'
      url: '/blog'
    - title: 'Demo'
      url: '/demo'

footer_settings:
  logo_image: 
  logo_width: 200
  footer_tagline: Working Group Two

grid_settings:
  overlay_opacity: 0.1
  grid_spacing: 10

contact_settings:
  form_action: 'https://formspree.io/somethinghere'
  confirmation_url: '/'
  email_subject: 'Message from wgtwo.com'
  send_button_text: 'Submit'


#home 
color_settings:
  background_color: '#274779'
  background_alt_color: '#f4f5f6'
  text_dark_color: '#EFE4E4' #'#ABB7B7'
  text_medium_color: '#6C7A89'
  text_light_color: '#ABB7B7'
  accent_color: '#ffffff'
  border_color: '#dddddd'
  overlay_background_color: '#000000' #'#F2784B'
  overlay_text_color: '#ABB7B7'
  overlay_accent_color: '#ABB7B7'
  error_color: '#D64541'

color_settings_customer_stories:
  background_color: '#5d3e59'
  text_dark_color: '#c28c69' #h1,h2,h3,-h6
  text_light_color: '#ABB7B7' #p
  # accent_color: '#ffffff'
  # border_color: '#dddddd'
  # overlay_background_color: '#000000' #'#F2784B'
  # overlay_text_color: '#ABB7B7'
  # overlay_accent_color: '#ABB7B7'
  # error_color: '#D64541'

color_settings_why_wgtwo:
  background_color: '#9f634f'
  text_dark_color: '#f0e6e2' #h1,h2,h3,-h6
  text_light_color: '#ABB7B7' #p

color_settings_blog:
  background_color: '#f0e6e2'
  text_dark_color: '#2a3870' #h1,h2,h3,-h6
  text_light_color: '#ABB7B7' #p

color_settings_demo:
  background_color: '#428c92'
  text_dark_color: '#2a3870' #h1,h2,h3,-h6
  text_light_color: '#ABB7B7' #p

font_settings:
  # font_embed: '<link href="https://fonts.googleapis.com/css?family=VT323&display=swap":300,400,600,700" rel="stylesheet">'
  # custom font in _basic.scss
  title_font: '"noe-display"'
  body_font: '"SpotMono"'
  regular_weight: 400
  bold_weight: 600
  site_title:
    small_size: 25
    medium_size: 30
    large_size: 35
    weight: 100
    letter_spacing: -0.02
  menu:
    small_size: 18
    medium_size: 18
    large_size: 18
    weight: 400
    letter_spacing: 0
  grid_item_title:
    small_size: 22
    medium_size: 30
    large_size: 35
    weight: 700
    letter_spacing: -0.02
  grid_item_subtitle:
    small_size: 15
    medium_size: 17
    large_size: 19
    weight: 400
    letter_spacing: 0
  h1:
    small_size: 40
    medium_size: 50
    large_size: 60
    weight: 600
    letter_spacing: 0.0
    line_height: 1.2
  h2:
    small_size: 30
    medium_size: 40
    large_size: 50
    weight: 300
    letter_spacing: 0
    line_height: 1.2
  h3:
    small_size: 20
    medium_size: 30
    large_size: 40
    weight: 300
    letter_spacing: 0
    line_height: 1.3
  h4:
    small_size: 10
    medium_size: 15
    large_size: 20
    weight: 300
    letter_spacing: 0
    line_height: 1.6
  h5:
    small_size: 17
    medium_size: 20
    large_size: 20
    weight: 300
    letter_spacing: 0
    line_height: 1.6
  h6:
    small_size: 17
    medium_size: 20
    large_size: 20
    weight: 100
    letter_spacing: 0
    line_height: 1.6
  p:
    small_size: 15
    medium_size: 17
    large_size: 19
    weight: 400
    letter_spacing: 0
    line_height: 1.6
  blockquote:
    small_size: 25
    medium_size: 35
    large_size: 45
    weight: 300
    letter_spacing: -0.02
    line_height: 1.6
  buttons:
    weight: 600
    letter_spacing: 0

advanced_settings:
  ajax_loading: true
  analytics_code: 
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-58630348-7"></script>
    <script>
    </script>
  custom_styles: ""
  header_js: 
    <!-- Hotjar Tracking Code for https://www.wgtwo.com -->
    <script>
    </script>
  footer_js: ""